/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type UserTransformer from '#transformers/user_transformer'
import type ProductTransformer from '#transformers/product_transformer'
import type RawMaterialTransformer from '#transformers/raw_material_transformer'

export namespace Data {
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Product = InferData<ProductTransformer>
  export namespace Product {
    export type Variants = InferVariants<ProductTransformer>
  }
  export type RawMaterial = InferData<RawMaterialTransformer>
  export namespace RawMaterial {
    export type Variants = InferVariants<RawMaterialTransformer>
  }
}
