/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class ForgeSchema extends BaseModel {
  static $columns = ['id', 'productId', 'createdAt', 'updatedAt'] as const
  $columns = ForgeSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductRawMaterialSchema extends BaseModel {
  static $columns = ['id', 'productId', 'rawMaterialId', 'quantityNeeded', 'createdAt'] as const
  $columns = ProductRawMaterialSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column()
  declare rawMaterialId: string
  @column()
  declare quantityNeeded: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['id', 'name', 'price', 'createdAt', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare price: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RawMaterialSchema extends BaseModel {
  static $columns = ['id', 'name', 'quantity', 'createdAt', 'updatedAt'] as const
  $columns = RawMaterialSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare quantity: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
